### ISSUE TITLE
2023-06-27 TIP Caribbean FIS Full Tag Up

### ISSUE THREAD

**Issue by AdyanRios-NOAA** [SEFSC/SEFSC-SFD-CFB-TIP-Compositions#3]
## Agenda for June 27
- Review Tasks listed in GitHub issue
- Review google drive setup

## Progress 
Last full team meeting was June 13; Next one is July 12
### Administrative/Organizational
- [x] Updated [project timeline](https://docs.google.com/spreadsheets/d/1s4X3rlDCLAchpJJ8m7ru_WkNvU5KbiERu9RidlP0vF4/edit#gid=1178152487) in PIMS 
- [x] Established [google drive folder](https://drive.google.com/drive/folders/1jXuc9mERsvOFm1D10PHuoB6MEapV9qw9) structure 6/16
- [x] [Start shared Zotero](https://www.zotero.org/groups/5105931/caribtip/library) for references
- [x] Connected/Repurposed GitHub Carib TIP repo to house project management issues 
- [x] Established working team interactions
   - [x] Scheduled standing meetings between Katherine and Steve 
   - [x] Established full team meeting check in frequency (~every two weeks)
- [x] Observed TIP port sampling new staff member training 6/15
- [x] Demo use of ROracle for extracting Caribbean TIP data
- [x] Documented sub-milestones particularly for initial milestones (see below)
- [x] Coordinated and requested access to access current data streams (pending IT oracle account)
- [x] Requested shared network space via helpdesk
   - [x] IT created a folder called FIS_Caribbean_TIP under M:\Cross-Division Dat 

### Start annotated list of resources and exploring data with figures
- [x] Start annotated list of resources and associated notes
   - [x] Retracing of edits to Steve’s original data that may not be reflected in TIP
   - [x] SEDAR 80 length/weight discrepancies

### Reach out to complementary projects for documents/google drive folders/updates/full proposal
- [x] [Advancing the use of technology for port sampling in the US Caribbean using image analysis for length composition](https://drive.google.com/drive/folders/1h1fzOauw7XzLaid1wO9yHKsTmg8TvCK9) (Kevin) 
- [x] [Finalizing Data Processing Framework and Interface to Enhance Data Provision for Southeast Stock Assessments and Fisheries Management](https://docs.google.com/document/d/1RAv1THF0hcPL7Cg1DEzEV5aIVCNOdQJN6THJLbh6UsY/edit) (Alan)
- [x] [Trip Interview Program (TIP) Error Identification and Data Flag System](https://docs.google.com/document/d/1Mi0JHX1QXSPDrgs8o_TkyySya_WsAxnY/edit) (Larry)

#### June
- Start exploring data with figures 
   - Flagging needs to include data visualization work (oddities are often only noted when the data are plotted)
- Reach out to projects for documents/updates
   - Better understand complementary projects
- Start annotated list of resources 
   - Revisit specific flags from existing work; identify additional relevant work

#### July
- Schedule status quo meetings for island specific (?) metadata review
- Identify trends in reporting consistency across variables (table showing what has been reported and with what consistency?)
- Revisit specific flags from existing work (S57, S46)
- Revisit sub-milestones

#### August
- Document new flags
- Finalize reference library of past efforts
- Revisit sub-milestones

### Milestone 3 - Develop data visualization to be programed - 10/6/2023
- Leverage documentation compiled for milestone 2
- Inform Milestone 4 - Develop data filtering and binning processes to be programed - 11/3/2023
