### ISSUE TITLE
2023-07-27 updates

### ISSUE THREAD

**Issue by KatGodwin-NOAA** [SEFSC/SEFSC-SFD-CFB-TIP-Compositions#5]
## Agenda for July 27 

1. Progress report:

   -    Data Flagging project
   -    Historical Data project

2.  Find a calendar coworking window 

## Progress 
Last full team meeting was July 13; Next one is August 24?

#### General 

- [x] Start using Quarto 

#### Data Flagging project

- [x] Began sub-milestone of "Identify trends in reporting consistency across variables"
- [x] Continued progress on sub-milestone "Explore data with figures"

#### Historical Data project

- [x] Create comparable tables from historical data and data pulled from Oracle
- [x] Begin comparison of values using RStudio 

#### July
- Start exploring data with figures (started)
   - Flagging needs to include data visualization work (oddities are often only noted when the data are plotted)
- Reach out to projects for documents/updates (Completed)
   - Better understand complementary projects
- Start annotated list of resources (started)
   - Revisit specific flags from existing work; identify additional relevant work
- Schedule status quo meetings for island specific (?) metadata review
- Identify trends in reporting consistency across variables (table showing what has been reported and with what consistency?) (started)
- Revisit specific flags from existing work (S57, S46)
- Revisit sub-milestones

#### August
- Document new flags
- Finalize reference library of past efforts
- Revisit sub-milestones

### Milestone 3 - Develop data visualization to be programed - 10/6/2023
- Leverage documentation compiled for milestone 2
- Inform Milestone 4 - Develop data filtering and binning processes to be programed - 11/3/2023

**Comment by mollystevens-noaa** [comment]
Coworking: 1.5-2hr window to commit time & space to focus on working on TIP together.  Continue to have full tag up meetings.  @KatGodwin-NOAA will set these up.
