### ISSUE TITLE
Full tag up 8/24/2023

### ISSUE THREAD

**Issue by KatGodwin-NOAA** [SEFSC/SEFSC-SFD-CFB-TIP-Compositions#7]
### Progress report:

   -    Data Flagging project
   -    Historical Data project

## Progress 
Last full team meeting was July 27; Next one is September 7?

#### Data Flagging project
- [x] Continued work with sub-milestone of "Identify trends in reporting consistency across variables"
    - Identified variables that have 0 and 100 percent reporting consistency for SEDAR species 
    - Began creating ggplots of variables with inconsistent reporting across PR and VI combined
    - Began creating ggplots of variables with inconsistent reporting across PR and VI separately 
    - Isolated variables with reporting consistency between 1-99% 
    - Notes taken in Quarto 
- [x] Continued progress on sub-milestone "Explore data with figures"

#### Historical Data project 
- [x] Developed plan of attack for historical/Oracle dataset comparison

    - Look at how many unique interviews there for a given date
        - Interview date vs historical vs oracle \# of interviews
        - Correct dates to historical dates
    - Areazip correction 
        - Look for sample_county_code table codes that have muni/county names that correspond to codes
        - Look in oracle tables and tip manuals
        - Once fixed, update reporting_area_zip
    - Match gear codes
    - Convert old species codes to itis
    - How many length records for each species
    - Possibly find # of matching and mismatching lengths
- [x] Started comparison with 2004 records and found:
    - Jan-April dates and Nov-Dec input dates are one day off of each other
    - Oracle has more records on any given input day than historical records (most likely a good thing) 

#### July
- Start exploring data with figures (started)
   - Flagging needs to include data visualization work (oddities are often only noted when the data are plotted)
- Reach out to projects for documents/updates (Completed)
   - Better understand complementary projects
- Start annotated list of resources (started)
   - Revisit specific flags from existing work; identify additional relevant work
- Schedule status quo meetings for island specific (?) metadata review
- Identify trends in reporting consistency across variables (table showing what has been reported and with what consistency?) (started)
- Revisit specific flags from existing work (S57, S46)
- Revisit sub-milestones

#### August
- Document new flags
- Finalize reference library of past efforts
- Revisit sub-milestones

### Milestone 3 - Develop data visualization to be programed - 10/6/2023
- Leverage documentation compiled for milestone 2
- Inform Milestone 4 - Develop data filtering and binning processes to be programed - 11/3/2023
